/**
 * Compares a duplicated P1 site against the export it was built from.
 *
 * Reports per-workstream document and published counts, then checks the main
 * workstream document by document: presence, published state, locale tag,
 * template binding, translation edges. Read-only.
 *
 * Usage: TARGET_SITE=<uuid> [EXPORT_FILE=<path>] node scripts/verify-p1-copy.mjs
 */
import { readFileSync } from "node:fs";
import { api } from "./p1-admin.mjs";

const T = process.env.TARGET_SITE;
if (!T) throw new Error("Set TARGET_SITE to the site id to verify.");
const data = JSON.parse(readFileSync(process.env.EXPORT_FILE ?? `${process.env.SP}/glu-export/glu-full.json`, "utf8"));

// Artifacts of the template-path collision, and anything else parked aside.
const isJunk = (p) => p.startsWith("zz-preimport/") || p.startsWith("zz-");

const { branches } = await api(`/api/sites/${T}/branches`);

console.log("workstream           source docs/pub   target docs/pub   checkpoints");
for (const sb of data.branches) {
  const t = branches.find((b) => b.name === sb.branch.name) ?? branches.find((b) => b.isMain && sb.branch.isMain);
  if (!t) { console.log(`  ${sb.branch.name}: MISSING on target`); continue; }
  const { documents } = await api(`/api/sites/${T}/branches/${t.id}/documents`);
  const real = documents.filter((d) => !isJunk(d.path));
  const cps = await api(`/api/sites/${T}/branches/${t.id}/checkpoints`).catch(() => ({ checkpoints: [] }));
  const sPub = sb.documents.filter((d) => d.document.isPublished).length;
  const tPub = real.filter((d) => d.isPublished).length;
  console.log(
    `  ${(sb.branch.name || "?").padEnd(18)} ${String(sb.documents.length).padStart(3)}/${String(sPub).padEnd(3)}` +
      `          ${String(real.length).padStart(3)}/${String(tPub).padEnd(3)}          ${(cps.checkpoints ?? []).length}`,
  );
}

// ---- main workstream, document by document -------------------------------
const src = data.branches.find((b) => b.branch.isMain);
const B = branches.find((b) => b.isMain).id;
const { documents } = await api(`/api/sites/${T}/branches/${B}/documents`);
const tgt = new Map(documents.map((d) => [d.path, d]));

const { templates } = await api(`/api/sites/${T}/branches/${B}/templates`);
const tplNameByOldId = Object.fromEntries(data.templates.map((t) => [t.id, t.name]));
const tplIdByName = Object.fromEntries((templates ?? []).map((t) => [t.name, t.id]));

const missing = [], pubMismatch = [], localeMismatch = [], tplMismatch = [];
// _datasources/* are regenerated by template creation, so the source's own
// copies are not expected to appear as documents here.
const compared = src.documents.filter(
  (d) => !isJunk(d.document.path) && !d.document.path.startsWith("_datasources/"),
);
for (const d of compared) {
  const path = d.document.path;
  const t = tgt.get(path);
  if (!t) { missing.push(path); continue; }
  if (!!t.isPublished !== !!d.document.isPublished) {
    pubMismatch.push(`${path} src=${!!d.document.isPublished} tgt=${!!t.isPublished}`);
  }
  if ((t.locale ?? null) !== (d.document.locale ?? null)) {
    localeMismatch.push(`${path} src=${d.document.locale} tgt=${t.locale}`);
  }
  const wantTpl = d.document.templateId ? tplIdByName[tplNameByOldId[d.document.templateId]] : null;
  if ((t.templateId ?? null) !== (wantTpl ?? null)) tplMismatch.push(path);
}

const report = (label, list) => {
  console.log(`${label.padEnd(28)} ${list.length}`);
  list.slice(0, 6).forEach((m) => console.log("   " + m));
};
console.log(`\nmain: ${compared.length} source docs compared, ${documents.length} present on target`);
report("missing:", missing);
report("published mismatch:", pubMismatch);
report("locale mismatch:", localeMismatch);
report("template binding mismatch:", tplMismatch);

let edges = 0;
for (const d of compared.filter((x) => (x.variants ?? []).length)) {
  const id = tgt.get(d.document.path)?.id;
  if (!id) continue;
  const r = await api(`/api/sites/${T}/branches/${B}/documents/${id}/translations`).catch(() => null);
  edges += (r?.variants ?? []).length;
}
console.log(`\ntranslation edges rebuilt:   ${edges}`);
const dss = await api(`/api/sites/${T}/branches/${B}/datasources`).catch(() => ({ datasources: [] }));
console.log(`datasources on target:       ${(dss.datasources ?? []).map((x) => x.name ?? x.id).join(", ")}`);

const junk = documents.filter((d) => isJunk(d.path));
console.log(`leftover import artifacts:   ${junk.length}`);
for (const d of junk) console.log(`   ${d.path}  ${d.id}`);

const bad = missing.length + pubMismatch.length + localeMismatch.length + tplMismatch.length;
console.log(`\n${bad === 0 ? "clean" : `${bad} discrepancy(ies)`}`);
process.exitCode = bad === 0 ? 0 : 1;
